name: Continuous Delivery

on:
  push:
    branches:
      - main
      - release
    paths-ignore:
      - "./.github/CODE_OF_CONDUCT.md"
      - "./.github/CONTRIBUTING.md"
      - "./.github/GOVERNANCE.md"
      - "./.github/ISSUE_TEMPLATE/*"
      - "./.github/pull_request_template.md"
      - "./.github/SECURITY.md"
      - "./.github/SUPPORT.md"
      - "./images/*"
      - "./README.md"

permissions:
  contents: read

jobs:
  linting:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Action | Validate Commit Messages
        uses: opensource-nepal/commitlint@v1
      - name: Action | Validate PR Title
        uses: CashStory/commitizen-action-pr@1.0.1

  release:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref_name }}
      cancel-in-progress: false

    permissions:
      contents: write

    steps:
      - name: Setup | Checkout Repository on Release Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup | Force Release Branch to be at Workflow SHA
        run: |
          git reset --hard ${{ github.sha }}

      - name: Evaluate | Verify Upstream has NOT Changed
        shell: bash
        run: |
          set +o pipefail

          UPSTREAM_BRANCH_NAME="$(git status -sb | head -n 1 | awk -F '\\.\\.\\.' '{print $2}' | cut -d ' ' -f1)"
          printf '%s\n' "Upstream branch name: $UPSTREAM_BRANCH_NAME"

          set -o pipefail

          if [ -z "$UPSTREAM_BRANCH_NAME" ]; then
              printf >&2 '%s\n' "::error::Unable to determine upstream branch name!"
              exit 1
          fi

          git fetch "${UPSTREAM_BRANCH_NAME%%/*}"

          if ! UPSTREAM_SHA="$(git rev-parse "$UPSTREAM_BRANCH_NAME")"; then
              printf >&2 '%s\n' "::error::Unable to determine upstream branch sha!"
              exit 1
          fi

          HEAD_SHA="$(git rev-parse HEAD)"

          if [ "$HEAD_SHA" != "$UPSTREAM_SHA" ]; then
              printf >&2 '%s\n' "[HEAD SHA] $HEAD_SHA != $UPSTREAM_SHA [UPSTREAM SHA]"
              printf >&2 '%s\n' "::error::Upstream has changed, aborting release..."
              exit 1
          fi

          printf '%s\n' "Verified upstream branch has not changed, continuing with release..."

      - name: Bundle | Prepare Artifacts
        run: |
          zip -r notebooks.zip ./notebooks/

      - name: Action | Create Semantic Version Release
        id: release
        uses: python-semantic-release/python-semantic-release@v10.4.1
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN_ADMIN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"
          config_file: "./releaserc.toml"
          verbosity: 1

      - name: Action | Publish to GitHub Release Assets
        uses: python-semantic-release/publish-action@v10.4.1
        if: steps.release.outputs.released == 'true'
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN_ADMIN }}
          tag: ${{ steps.release.outputs.tag }}

      - name: Action | Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: notebooks
          path: "./notebooks/"
          if-no-files-found: error

    outputs:
      released: ${{ steps.release.outputs.released || 'false' }}
