name: Continuous Delivery

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release

permissions:
  contents: read

jobs:
  linting:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Action | Validate PR Title
        if: github.event_name == 'pull_request'
        uses: CashStory/commitizen-action-pr@1.0.1

      - name: Action | Validate Commit Messages
        uses: opensource-nepal/commitlint@v1

  release:
    runs-on: ubuntu-latest
    needs: linting
    concurrency:
      group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref_name }}
      cancel-in-progress: false

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Action | Create GitHub App Token
        uses: actions/create-github-app-token@v2
        id: action-create-github-app-token
        with:
          app-id: ${{ vars.APP_ID_GITHUB_APP_BYPASS_RULESETS }}
          private-key: ${{ secrets.PRIVATE_KEY_GITHUB_APP_BYPASS_RULESETS }}

      - name: Setup | Checkout Repository on Release Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          token: ${{ steps.action-create-github-app-token.outputs.token }}

      - name: Setup | Force Release Branch to be at Workflow SHA
        run: |
          git reset --hard ${{ github.sha }}

      - name: Evaluate | Verify Upstream has NOT Changed
        shell: bash
        run: |
          set +o pipefail

          UPSTREAM_BRANCH_NAME="$(git status -sb | head -n 1 | awk -F '\\.\\.\\.' '{print $2}' | cut -d ' ' -f1)"
          printf '%s\n' "Upstream branch name: $UPSTREAM_BRANCH_NAME"

          set -o pipefail

          if [ -z "$UPSTREAM_BRANCH_NAME" ]; then
              printf >&2 '%s\n' "::error::Unable to determine upstream branch name!"
              exit 1
          fi

          git fetch "${UPSTREAM_BRANCH_NAME%%/*}"

          if ! UPSTREAM_SHA="$(git rev-parse "$UPSTREAM_BRANCH_NAME")"; then
              printf >&2 '%s\n' "::error::Unable to determine upstream branch sha!"
              exit 1
          fi

          HEAD_SHA="$(git rev-parse HEAD)"

          if [ "$HEAD_SHA" != "$UPSTREAM_SHA" ]; then
              printf >&2 '%s\n' "[HEAD SHA] $HEAD_SHA != $UPSTREAM_SHA [UPSTREAM SHA]"
              printf >&2 '%s\n' "::error::Upstream has changed, aborting release..."
              exit 1
          fi

          printf '%s\n' "Verified upstream branch has not changed, continuing with release..."

      - name: Bundle | Prepare Artifacts
        run: |
          zip -r notebooks.zip ./notebooks/

      - name: Action | Create Semantic Version Release
        id: python-semantic-release-release
        uses: python-semantic-release/python-semantic-release@v10.4.1
        with:
          github_token: ${{ steps.action-create-github-app-token.outputs.token }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"
          config_file: "./releaserc.toml"
          verbosity: 1

      - name: Action | Publish to GitHub Release Assets
        uses: python-semantic-release/publish-action@v10.4.1
        if: steps.python-semantic-release-release.outputs.released == 'true'
        with:
          github_token: ${{ steps.action-create-github-app-token.outputs.token }}
          tag: ${{ steps.python-semantic-release-release.outputs.tag }}

      - name: Action | Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: notebooks
          path: "./notebooks/"
          if-no-files-found: error

    outputs:
      released: ${{ steps.python-semantic-release-release.outputs.released || 'false' }}
